### ISSUE TITLE
依赖的NanomsgNG.NET哪里下载

### ISSUE THREAD

**Issue by pcstx** [send010/WeChatFerry-CSharp#2]
C:\Users\Administrator\Downloads\NanomsgNG.NET-master\nng.NET\nng.NET.csproj
这个我应该从哪里下载呢？

**Comment by send010** [comment]
github NanomsgNG.NET

**Comment by send010** [comment]
不好意思打错了 替换成 nuget的NanomsgNG.NET就好 我把最新的给推送上来
