### ISSUE TITLE
获取不到通讯录

### ISSUE THREAD

**Issue by 16bd** [send010/WeChatFerry-CSharp#5]
其他功能一切正常，就是获取不到通讯录，请问知道怎么回事吗？

**Comment by send010** [comment]
可能是DLL不支持 你可以从db文件里面读取

**Comment by xyhui83** [comment]
用WechatFerry打包的dll就可以

**Comment by send010** [comment]
> 用WechatFerry打包的dll就可以

应该是最近更新了，我打包的比较早。
